# Generated by Django 2.1.2 on 2019-03-08 06:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentJournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
