# Generated by Django 2.1.2 on 2019-03-08 06:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        ('school', '0001_initial'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentjournalentry',
            name='mptt_syllabus',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.MPTTSyllabus'),
        ),
        migrations.AddField(
            model_name='studentjournalentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
        migrations.AddField(
            model_name='studentjournalentry',
            name='syllabus_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.SyllabusPoint'),
        ),
        migrations.AddField(
            model_name='studentjournalentry',
            name='syllabus_sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.SyllabusSubTopic'),
        ),
        migrations.AlterUniqueTogether(
            name='studentjournalentry',
            unique_together={('student', 'syllabus_point'), ('student', 'syllabus_sub_topic')},
        ),
    ]
