# Generated by Django 2.0.1 on 2019-03-03 09:11

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190303_1711'),
        ('journal', '0002_auto_20181123_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentjournalentry',
            name='mptt_syllabus',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.MPTTSyllabus'),
        ),
    ]
