# Generated by Django 2.0.1 on 2019-01-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20181123_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
