# Generated by Django 2.1.2 on 2019-03-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190308_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaders', models.ManyToManyField(blank=True, to='school.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='KeyStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaders', models.ManyToManyField(blank=True, to='school.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaders', models.ManyToManyField(blank=True, to='school.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='YearGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.KeyStage')),
                ('leaders', models.ManyToManyField(blank=True, to='school.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='keystage',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Phase'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='leaders',
            field=models.ManyToManyField(blank=True, to='school.Teacher'),
        ),
    ]
