# Generated by Django 2.0.1 on 2019-03-03 09:11

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190303_1711'),
        ('school', '0003_classgroup_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='mptt_syllabustaught',
            field=mptt.fields.TreeManyToManyField(to='tracker.MPTTSyllabus'),
        ),
    ]
