# Generated by Django 2.1.7 on 2019-05-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_classgroup_mptt_syllabustaught'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PastoralStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='eal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='learning_support',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('SA', 'SA'), ('M', 'M'), ('SS', 'SS'), ('N', 'N')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='groupteacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Teacher'),
        ),
        migrations.AddField(
            model_name='pastoralstructure',
            name='classgroups',
            field=models.ManyToManyField(blank=True, to='school.ClassGroup'),
        ),
    ]
