# Generated by Django 2.1.7 on 2019-03-18 05:50

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20190315_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_tutorgroup',
            field=mptt.fields.TreeOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.AcademicStructure'),
        ),
    ]
