# Generated by Django 2.1.7 on 2019-03-18 05:57

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20190318_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_tutorgroup',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.PastoralStructure'),
        ),
    ]
