# Generated by Django 2.1.7 on 2019-06-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_classgroup_year_taught'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='rollover_classgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.ClassGroup'),
        ),
    ]
