# Generated by Django 2.1.7 on 2019-03-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20190318_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='groupteacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Teacher'),
        ),
    ]
