# Generated by Django 2.1.7 on 2019-03-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_kpipair_name'),
        ('school', '0009_auto_20190318_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicstructure',
            name='kpi_pairs',
            field=models.ManyToManyField(blank=True, to='tracker.KPIPair'),
        ),
        migrations.AddField(
            model_name='pastoralstructure',
            name='kpi_pairs',
            field=models.ManyToManyField(blank=True, to='tracker.KPIPair'),
        ),
    ]
