# Generated by Django 2.1.7 on 2019-03-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_tutorgroup_pastoral_link'),
    ]

    operations = [
    ]
