# Generated by Django 2.1.7 on 2019-03-19 05:57

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20190319_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorgroup',
            name='pastoral_link',
            field=mptt.fields.TreeOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.PastoralStructure'),
        ),
    ]
