# Generated by Django 2.1.7 on 2019-03-19 05:57


from django.db import migrations

def link_tgs(apps, schema_editor):
    TutorGroup = apps.get_models('school', 'TutorGroup')
    PastoralStructure = apps.get_models('school', 'PastoralStructure')

    tgs = TutorGroup.objects.all()
    for tg in tgs:
        pastoral_tg, created = PastoralStructure.objects.get_or_create(name=tg.tgname)
        if created:
            # Could include code to insert to correct year
            pass
        tg.pastoral_link = pastoral_tg
        tg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20190319_1357'),
    ]

    operations = [
        migrations.RunPython(link_tgs)
    ]
