# Generated by Django 2.1.7 on 2019-04-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20190319_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicstructure',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pastoralstructure',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
