# Generated by Django 2.1.7 on 2019-04-11 00:59

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20190411_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='academic_position',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.AcademicStructure'),
        ),
    ]
