# Generated by Django 2.1.7 on 2019-04-11 01:00

from django.db import migrations
import re


def link_classgroups(apps, schema_editor):
    ClassGroup = apps.get_model('school', 'ClassGroup')
    AcademicStructure = apps.get_model('school', 'AcademicStructure')

    groups = ClassGroup.objects.all()

    primary_science, created = AcademicStructure.objects.get_or_create(name='Primary Sciences', defaults={'lft': 0,
                                                                                                          'rght': 0,
                                                                                                          'level': 0,
                                                                                                          'tree_id': 0})
    primary_maths, created = AcademicStructure.objects.get_or_create(name='Primary Mathematics', defaults={'lft': 0,
                                                                                                           'rght': 0,
                                                                                                           'level': 0,
                                                                                                           'tree_id': 0})

    primary_english, created = AcademicStructure.objects \
        .get_or_create(name='Primary English',
                       defaults={'lft': 0,
                                 'rght': 0,
                                 'level': 0,
                                 'tree_id': 0})

    for group in groups:
        academic_group, created = AcademicStructure.objects \
            .get_or_create(name=group.groupname,
                           defaults={'lft': 0,
                                     'rght': 0,
                                     'level': 0,
                                     'tree_id': 0})
        group.academic_position = academic_group

        if re.search('Sciences', group.groupname):
            academic_group.parent = primary_science
        if re.search('English', group.groupname):
            academic_group.parent = primary_english
        if re.search('Mathematics', group.groupname):
            academic_group.parent = primary_maths

        academic_group.save()


class Migration(migrations.Migration):
    dependencies = [
        ('school', '0016_classgroup_academic_position'),
    ]

    operations = [
        migrations.RunPython(link_classgroups)
    ]
