# Generated by Django 2.1.7 on 2019-04-11 01:06

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20190411_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='academic_position',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.AcademicStructure'),
        ),
    ]
