# Generated by Django 2.1.7 on 2019-04-11 03:25

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20190411_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='academic_position',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.AcademicStructure'),
        ),
    ]
