# Generated by Django 2.1.2 on 2019-03-08 06:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0002_auto_20190308_1413'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('lesson_title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('sequence', models.IntegerField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('classgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.ClassGroup')),
            ],
        ),
        migrations.CreateModel(
            name='LessonResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('Presentation', 'Presentation'), ('Worksheet', 'Worksheet'), ('Test', 'Test'), ('Mark Scheme', 'Mark Scheme'), ('Web Page', 'Web Page')], max_length=100, null=True)),
                ('resource_name', models.CharField(max_length=100, null=True)),
                ('link', models.URLField(null=True)),
                ('students_can_view_before', models.BooleanField(default=False)),
                ('students_can_view_after', models.BooleanField(default=False)),
                ('available_to_all_classgroups', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Lesson')),
                ('mptt_syllabus_points', mptt.fields.TreeManyToManyField(to='tracker.MPTTSyllabus')),
                ('syllabus_points', models.ManyToManyField(blank=True, to='tracker.SyllabusPoint')),
            ],
        ),
        migrations.CreateModel(
            name='LessonSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('period', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
            ],
        ),
        migrations.CreateModel(
            name='LessonSuspension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whole_school', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=200, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('period', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('classgroups', models.ManyToManyField(blank=True, to='school.ClassGroup')),
            ],
        ),
        migrations.CreateModel(
            name='TimetabledLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.ClassGroup')),
                ('lesson_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.LessonSlot')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lessonslot',
            unique_together={('day', 'period')},
        ),
        migrations.AddField(
            model_name='lesson',
            name='lessonslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.TimetabledLesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='mptt_syllabus_points',
            field=mptt.fields.TreeManyToManyField(blank=True, to='tracker.MPTTSyllabus'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Syllabus'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='syllabus_points_covered',
            field=models.ManyToManyField(blank=True, to='tracker.SyllabusPoint'),
        ),
        migrations.AlterUniqueTogether(
            name='timetabledlesson',
            unique_together={('classgroup', 'lesson_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('classgroup', 'sequence'), ('lessonslot', 'date')},
        ),
    ]
