# Generated by Django 2.0.1 on 2019-03-03 09:11

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190303_1711'),
        ('timetable', '0003_auto_20190105_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='mptt_syllabus_points',
            field=mptt.fields.TreeManyToManyField(blank=True, to='tracker.MPTTSyllabus'),
        ),
        migrations.AddField(
            model_name='lessonresources',
            name='mptt_syllabus_points',
            field=mptt.fields.TreeManyToManyField(to='tracker.MPTTSyllabus'),
        ),
    ]
