# Generated by Django 2.1.7 on 2019-06-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20190303_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonslot',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
