# Generated by Django 2.1.7 on 2019-06-12 01:41
# Comment out this import later; used for autocomplete
#from timetable.models import LessonSlot
from django.db import migrations

def add_default_year(apps, schema_editor):
    LessonSlot = apps.get_model("timetable", "LessonSlot")
    LessonSlot.objects.all().update(year=0)

class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_lessonslot_year'),
    ]

    operations = [
        migrations.RunPython(add_default_year)
    ]
