# Generated by Django 2.1.7 on 2019-06-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_add_default_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonslot',
            name='year',
            field=models.IntegerField(),
        ),
    ]
