# Generated by Django 2.2.4 on 2019-08-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_auto_20190830_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='links',
        ),
    ]
