# Generated by Django 2.2.4 on 2019-08-30 03:45
#from timetable.models import Lesson, LessonResources
from django.db import migrations

def add_initial_lesson(apps, schema_editor):
    LessonResources = apps.get_model("timetable", "LessonResources")

    resources = LessonResources.objects.filter(lesson__isnull=False)

    for resource in resources:
        resource.lessons.add(resource.lesson)


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_lessonresources_lessons'),
    ]

    operations = [
        migrations.RunPython(add_initial_lesson)
    ]
