# Generated by Django 2.2.4 on 2019-08-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_auto_20190830_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonresources',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='lessonresources',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lessonresources',
            name='lesson',
            field=models.ManyToManyField(blank=True, to='timetable.Lesson'),
        ),
    ]
