# Generated by Django 2.2.4 on 2019-08-30 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_auto_20190830_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sethomework',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='sethomework',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonresources',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lessonresources',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Lesson'),
        ),
        migrations.AlterField(
            model_name='lessonresources',
            name='resource_type',
            field=models.CharField(choices=[('Presentation', 'Presentation'), ('Worksheet', 'Worksheet'), ('Test', 'Test'), ('Mark Scheme', 'Mark Scheme'), ('Web Page', 'Web Page')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='SetHomework',
        ),
    ]
