# Generated by Django 2.2.4 on 2019-08-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_auto_20190830_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
