# Generated by Django 2.2.4 on 2019-09-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_lesson_homework_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresources',
            name='resource_type',
            field=models.CharField(choices=[('Presentation', 'Presentation'), ('Worksheet', 'Worksheet'), ('Test', 'Test'), ('Mark Scheme', 'Mark Scheme'), ('Web Page', 'Web Page'), ('Google Drive', 'Google Drive')], max_length=100, null=True),
        ),
    ]
