# Generated by Django 2.0.1 on 2018-11-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qimage', models.ImageField(upload_to='qimages')),
                ('year', models.IntegerField()),
                ('paper', models.CharField(max_length=10)),
                ('qnumber', models.IntegerField()),
                ('aimage', models.ImageField(upload_to='aimages')),
            ],
        ),
    ]
