# Generated by Django 2.0.1 on 2018-11-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0001_initial'),
        ('exambuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Syllabus'),
        ),
    ]
