# Generated by Django 2.0.1 on 2018-11-25 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20181123_1532'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPointRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(default='Calculated', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
                ('syllabus_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.SyllabusPoint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSubTopicRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(default='Calculated', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
                ('syllabus_sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.SyllabusSubTopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSyllabusRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(default='Calculated', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Syllabus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTopicRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(default='Calculated', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
                ('syllabus_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.SyllabusTopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'question', 'sitting')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam', 'qorder')},
        ),
    ]
