# Generated by Django 2.1.2 on 2019-03-08 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardiseddata',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='standardisedresult',
            name='standardised_data',
        ),
        migrations.RemoveField(
            model_name='standardisedresult',
            name='student',
        ),
        migrations.AlterField(
            model_name='mpttrating',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 14, 14, 50, 350994)),
        ),
        migrations.DeleteModel(
            name='StandardisedData',
        ),
        migrations.DeleteModel(
            name='StandardisedResult',
        ),
    ]
