# Generated by Django 2.0.1 on 2018-01-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=50)),
                ('groupteacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Teacher')),
            ],
        ),
    ]
