# Generated by Django 2.0.1 on 2019-01-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20181125_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpointrating',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsubtopicrating',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsyllabusrating',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studenttopicrating',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
