# Generated by Django 2.0.1 on 2018-02-07 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0003_auto_20180207_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Undisclosed', 'Undisclosed')], max_length=20)),
                ('idnumber', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgname', models.CharField(max_length=5)),
                ('tgtutor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Teacher')),
            ],
        ),
        migrations.RenameModel(
            old_name='Group',
            new_name='ClassGroup',
        ),
        migrations.AddField(
            model_name='student',
            name='tg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.TutorGroup'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
