# Generated by Django 2.0.1 on 2019-03-03 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_classgroup_archived'),
        ('tracker', '0003_auto_20190128_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPTTRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('zero_to_one', models.IntegerField(blank=True, null=True)),
                ('one_to_two', models.IntegerField(blank=True, null=True)),
                ('two_to_three', models.IntegerField(blank=True, null=True)),
                ('three_to_four', models.IntegerField(blank=True, null=True)),
                ('four_to_five', models.IntegerField(blank=True, null=True)),
                ('total_contributions', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 3, 3, 17, 11, 38, 321876))),
                ('reason', models.CharField(default='Assessment', max_length=100)),
                ('assessment', models.ManyToManyField(to='tracker.Sitting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
        ),
        migrations.CreateModel(
            name='MPTTSyllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('tier', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracker.MPTTSyllabus')),
                ('related_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.SyllabusPoint')),
                ('related_sub_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.SyllabusSubTopic')),
                ('related_syllabus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Syllabus')),
                ('related_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.SyllabusTopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='weighting',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='mark',
            name='maximum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='percent',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='updates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mark',
            name='weighted_maximum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='weighted_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='weighting',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='syllabuspoint',
            field=models.ManyToManyField(blank=True, to='tracker.SyllabusPoint'),
        ),
        migrations.AddField(
            model_name='mpttrating',
            name='syllabus',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.MPTTSyllabus'),
        ),
        migrations.AddField(
            model_name='question',
            name='MPTTsyllabuspoint',
            field=mptt.fields.TreeManyToManyField(to='tracker.MPTTSyllabus'),
        ),
    ]
