# Generated by Django 2.1.7 on 2019-05-17 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20190517_1642'),
        ('tracker', '0004_auto_20190303_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PastStandardisedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('date_created', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('reason_created', models.TextField(blank=True, null=True)),
                ('residual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardisedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('min_value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('step', models.DecimalField(decimal_places=1, max_digits=5)),
                ('quickname', models.CharField(blank=True, max_length=20, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracker.StandardisedData')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardisedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(decimal_places=1, max_digits=5)),
                ('target', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('date_created', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('reason_created', models.TextField(blank=True, null=True)),
                ('residual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('normalised_residual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('standardised_data', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.StandardisedData')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='mark',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mpttrating',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='studentpointrating',
            name='current',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='studentsubtopicrating',
            name='current',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='studentsyllabusrating',
            name='current',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='studenttopicrating',
            name='current',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='paststandardisedresult',
            name='standardised_data',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.StandardisedData'),
        ),
        migrations.AddField(
            model_name='paststandardisedresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
        migrations.AddField(
            model_name='kpipair',
            name='student_result',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_result', to='tracker.StandardisedData'),
        ),
        migrations.AddField(
            model_name='kpipair',
            name='sudent_target',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_target', to='tracker.StandardisedData'),
        ),
    ]
