# Generated by Django 2.1.2 on 2019-03-11 07:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190311_1441'),
        ('tracker', '0004_auto_20190311_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastStandardisedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(decimal_places=1, max_digits=5)),
                ('target', models.DecimalField(decimal_places=1, max_digits=5)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('reason_created', models.TextField(blank=True, null=True)),
                ('standardised_data', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.StandardisedData')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
        ),
        migrations.AddField(
            model_name='standardisedresult',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AddField(
            model_name='standardisedresult',
            name='reason_created',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardisedresult',
            name='target',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mpttrating',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 15, 18, 3, 666986)),
        ),
    ]
