# Generated by Django 2.2.4 on 2019-10-01 03:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_classgroup_rollover_classgroup'),
        ('tracker', '0005_auto_20190517_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPTTManualRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('reason', models.CharField(default='Student Assessment', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
                ('syllabus', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.MPTTSyllabus')),
            ],
        ),
    ]
