# Generated by Django 2.2.4 on 2019-10-01 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_mpttmanualrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='root_syllabus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.MPTTSyllabus'),
        ),
    ]
