# Generated by Django 2.1.7 on 2019-03-15 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20190312_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardiseddata',
            name='quickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mpttrating',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 12, 12, 35, 302999)),
        ),
        migrations.AlterField(
            model_name='standardisedresult',
            name='target',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
