# Generated by Django 2.1.7 on 2019-03-18 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20190315_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpttrating',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 10, 37, 33, 739949)),
        ),
        migrations.AlterField(
            model_name='standardisedresult',
            name='residual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
