# Generated by Django 2.1.7 on 2019-03-18 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20190315_1212'),
        ('tracker', '0008_auto_20190318_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpttrating',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 10, 51, 44, 453810)),
        ),
        migrations.AlterField(
            model_name='paststandardisedresult',
            name='residual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='paststandardisedresult',
            name='result',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='paststandardisedresult',
            name='target',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),

    ]
