# Generated by Django 2.0.1 on 2018-02-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20180217_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='syllabuspoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Syllabuspoint'),
        ),
    ]
