# Generated by Django 2.1.7 on 2019-03-18 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20190318_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpttrating',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 10, 57, 2, 935552)),
        ),
        migrations.AlterField(
            model_name='paststandardisedresult',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 18, 10, 57, 2, 943949), null=True),
        ),
        migrations.AlterField(
            model_name='standardisedresult',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 18, 10, 57, 2, 941555), null=True),
        ),
    ]
