# Generated by Django 2.1.7 on 2019-03-18 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20190318_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpttrating',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 13, 57, 38, 76484)),
        ),
    ]
