# Generated by Django 2.1.7 on 2019-03-18 23:55

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_auto_20190318_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_result', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_result', to='tracker.StandardisedData')),
                ('sudent_target', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_target', to='tracker.StandardisedData')),
            ],
        ),
        migrations.AddField(
            model_name='standardisedresult',
            name='normalised_residual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
