# Generated by Django 2.1.7 on 2019-03-18 23:56

from django.db import migrations

def create_residuals(apps, schema_editor):
    StandardisedResult = apps.get_model('tracker', 'StandardisedResult')

    results = StandardisedResult.objects.filter(result__isnull=False, target__isnull=False)

    for result in results:
        result.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_auto_20190319_0755'),
    ]

    operations = [
        migrations.RunPython(create_residuals)
    ]
