# Generated by Django 2.1.7 on 2019-03-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_auto_20190319_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpipair',
            name='name',
            field=models.CharField(default='unnamed', max_length=100),
            preserve_default=False,
        ),
    ]
